name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@v0.0.9
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: |
          cd ${{ secrets.PATH }}
          git checkout main
          git pull